# TCL File Generated by Component Editor 13.0sp1
# Sun Jan 29 23:35:23 IRST 2023
# DO NOT MODIFY


# 
# Rgb2Gray_AvalonStream "Rgb2Gray_AvalonStream" v1.0
#  2023.01.29.23:35:23
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Rgb2Gray_AvalonStream
# 
set_module_property DESCRIPTION ""
set_module_property NAME Rgb2Gray_AvalonStream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Rgb2Gray_AvalonStream
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Rgb2Gray_AvalonStreaming
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Rgb2Gray_AvalonStreaming.v VERILOG PATH ../../../hdl/Rgb2Gray_AvalonStreaming.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point sink1
# 
add_interface sink1 avalon_streaming end
set_interface_property sink1 associatedClock clock_sink
set_interface_property sink1 associatedReset reset_sink
set_interface_property sink1 dataBitsPerSymbol 8
set_interface_property sink1 errorDescriptor ""
set_interface_property sink1 firstSymbolInHighOrderBits true
set_interface_property sink1 maxChannel 0
set_interface_property sink1 readyLatency 0
set_interface_property sink1 ENABLED true
set_interface_property sink1 EXPORT_OF ""
set_interface_property sink1 PORT_NAME_MAP ""
set_interface_property sink1 SVD_ADDRESS_GROUP ""

add_interface_port sink1 asi_sink1_data data Input 24
add_interface_port sink1 asi_sink1_startofpacket startofpacket Input 1
add_interface_port sink1 asi_sink1_endofpacket endofpacket Input 1
add_interface_port sink1 asi_sink1_valid valid Input 1
add_interface_port sink1 asi_sink1_ready ready Output 1


# 
# connection point source1
# 
add_interface source1 avalon_streaming start
set_interface_property source1 associatedClock clock_sink
set_interface_property source1 associatedReset reset_sink
set_interface_property source1 dataBitsPerSymbol 8
set_interface_property source1 errorDescriptor ""
set_interface_property source1 firstSymbolInHighOrderBits true
set_interface_property source1 maxChannel 0
set_interface_property source1 readyLatency 0
set_interface_property source1 ENABLED true
set_interface_property source1 EXPORT_OF ""
set_interface_property source1 PORT_NAME_MAP ""
set_interface_property source1 SVD_ADDRESS_GROUP ""

add_interface_port source1 aso_source1_ready ready Input 1
add_interface_port source1 aso_source1_data data Output 8
add_interface_port source1 aso_source1_startofpacket startofpacket Output 1
add_interface_port source1 aso_source1_endofpacket endofpacket Output 1
add_interface_port source1 aso_source1_valid valid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink csi_clock_reset_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink csi_clock_reset_reset_n reset_n Input 1

