# TCL File Generated by Component Editor 13.0sp1
# Mon Jan 30 02:08:32 IRST 2023
# DO NOT MODIFY


# 
# SobelFilter_AvalonStreaming "SobelFilter_AvalonStreaming" v1.9
#  2023.01.30.02:08:32
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module SobelFilter_AvalonStreaming
# 
set_module_property DESCRIPTION ""
set_module_property NAME SobelFilter_AvalonStreaming
set_module_property VERSION 1.9
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SobelFilter_AvalonStreaming
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SobelF
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SobelF.v VERILOG PATH ../../../hdl/SobelF.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IMG_X_SIZE INTEGER 320 ""
set_parameter_property IMG_X_SIZE DEFAULT_VALUE 320
set_parameter_property IMG_X_SIZE DISPLAY_NAME IMG_X_SIZE
set_parameter_property IMG_X_SIZE TYPE INTEGER
set_parameter_property IMG_X_SIZE UNITS None
set_parameter_property IMG_X_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMG_X_SIZE DESCRIPTION ""
set_parameter_property IMG_X_SIZE HDL_PARAMETER true
add_parameter IMG_Y_SIZE INTEGER 240 ""
set_parameter_property IMG_Y_SIZE DEFAULT_VALUE 240
set_parameter_property IMG_Y_SIZE DISPLAY_NAME IMG_Y_SIZE
set_parameter_property IMG_Y_SIZE TYPE INTEGER
set_parameter_property IMG_Y_SIZE UNITS None
set_parameter_property IMG_Y_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMG_Y_SIZE DESCRIPTION ""
set_parameter_property IMG_Y_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point sink1
# 
add_interface sink1 avalon_streaming end
set_interface_property sink1 associatedClock clkrst
set_interface_property sink1 associatedReset clkrst_reset
set_interface_property sink1 dataBitsPerSymbol 8
set_interface_property sink1 errorDescriptor ""
set_interface_property sink1 firstSymbolInHighOrderBits true
set_interface_property sink1 maxChannel 0
set_interface_property sink1 readyLatency 0
set_interface_property sink1 ENABLED true
set_interface_property sink1 EXPORT_OF ""
set_interface_property sink1 PORT_NAME_MAP ""
set_interface_property sink1 SVD_ADDRESS_GROUP ""

add_interface_port sink1 asi_sink1_data data Input 8
add_interface_port sink1 asi_sink1_startofpacket startofpacket Input 1
add_interface_port sink1 asi_sink1_endofpacket endofpacket Input 1
add_interface_port sink1 asi_sink1_valid valid Input 1
add_interface_port sink1 asi_sink1_ready ready Output 1


# 
# connection point source1
# 
add_interface source1 avalon_streaming start
set_interface_property source1 associatedClock clkrst
set_interface_property source1 associatedReset clkrst_reset
set_interface_property source1 dataBitsPerSymbol 8
set_interface_property source1 errorDescriptor ""
set_interface_property source1 firstSymbolInHighOrderBits true
set_interface_property source1 maxChannel 0
set_interface_property source1 readyLatency 0
set_interface_property source1 ENABLED true
set_interface_property source1 EXPORT_OF ""
set_interface_property source1 PORT_NAME_MAP ""
set_interface_property source1 SVD_ADDRESS_GROUP ""

add_interface_port source1 aso_source1_ready ready Input 1
add_interface_port source1 aso_source1_data data Output 8
add_interface_port source1 aso_source1_startofpacket startofpacket Output 1
add_interface_port source1 aso_source1_endofpacket endofpacket Output 1
add_interface_port source1 aso_source1_valid valid Output 1


# 
# connection point clkrst
# 
add_interface clkrst clock end
set_interface_property clkrst clockRate 0
set_interface_property clkrst ENABLED true
set_interface_property clkrst EXPORT_OF ""
set_interface_property clkrst PORT_NAME_MAP ""
set_interface_property clkrst SVD_ADDRESS_GROUP ""

add_interface_port clkrst csi_clkrst_clk clk Input 1


# 
# connection point clkrst_reset
# 
add_interface clkrst_reset reset end
set_interface_property clkrst_reset associatedClock clkrst
set_interface_property clkrst_reset synchronousEdges DEASSERT
set_interface_property clkrst_reset ENABLED true
set_interface_property clkrst_reset EXPORT_OF ""
set_interface_property clkrst_reset PORT_NAME_MAP ""
set_interface_property clkrst_reset SVD_ADDRESS_GROUP ""

add_interface_port clkrst_reset csi_clkrst_reset_n reset_n Input 1

